import {
  nido,
  HomeService,
  morningSide,
  BenilliEmpire,
  timeless,
  Project,
  FeniLogo,
  Neicy,
  ar3,
  Brooks,
  timelessBlack,
  focus,
  sriarch,
  majestic,
  landranc,
  vintage,
  bcbb,
  brooks,
  eici,
  WalmartBack1,
  WalmartBack2,
  WalmartBack3,
  WalmartBack4,
  ecommerceBack1,
  ecommerceBack2,
  ecommerceBack3,
  ecommerceBack4,
  WebDevBack1,
  WebDevBack2,
  WebDevBack3,
  WebDevBack4,
  GraphicBack1,
  GraphicBack2,
  GraphicBack3,
  GraphicBack4,
} from "../assets";

export const data = [
  {
    id: 1,
    mainTitle: "Walmart",
    portfolio: [
      {
        title: "Lanfranc Wholesale",
        category: "ecom",
        image: WalmartBack1,
        mainTitle: "Walmart",
        logo: landranc,
        link: "https://www.walmart.com/seller/101330914?itemId=861444937&pageName=item&returnUrl=%2Fip%2FCharmin-Ultra-Gentle-Toilet-Paper-6-Mega-Rolls-286-Sheets-Per-Roll%2F861444937",
        desc: "Walmart offers Lanfranc Wholesale, a one-stop shop offering high quality products at unbeatable prices, ensuring affordability and convenience for all your needs.",
      },
      {
        title: "SRIARSH",
        category: "ecom",
        image: WalmartBack2,
        mainTitle: "Walmart",
        logo: sriarch,
        link: "https://www.walmart.com/seller/101352648?itemId=557330560&pageName=item&returnUrl=%2Fip%2FWindex-Surface-Cleaners-Citrus-Scent-32-Fluid-Ounce%2F557330560",
        desc: "Walmart's one-stop shop, SRIARSH, offers a wide range of personal care and home essentials at unbeatable prices, transforming your everyday experience.",
      },
      {
        title: "Majestic Sellerz, LLC",
        category: "ecom",
        image: WalmartBack3,
        mainTitle: "Walmart",
        logo: majestic,
        link: "https://www.walmart.com/seller/101124625?itemId=481160050&pageName=item&returnUrl=%2Fip%2FKinetic-Sand-Construction-Site-Folding-Sandbox-Playset-with-Vehicle-and-2lbs-Kinetic-Sand-for-Kids-Aged-3-and-up%2F481160050",
        desc: "Majestic Sellerz offers a selection of household and daily necessities, and seasonal delights, providing a magnificent shopping experience for a wide range of products.",
      },
      {
        title: "Focus Marketing",
        category: "ecom",
        image: WalmartBack4,
        mainTitle: "Walmart",
        logo: focus,
        link: "https://www.walmart.com/seller/101288824?itemId=754320124&pageName=item&returnUrl=%2Fip%2FSoftsoap-Lustrous-Glow-Exfoliating-Body-Wash-Amber-and-Honey-20-Ounce%2F754320124",
        desc: "Focus Marketing offers a wide range of Household Essentials, focusing on quality, convenience, and personal care products to enhance your daily routine.",
      },
    ],
  },
  // {
  //   id: 2,
  //   mainTitle: "Amazon",
  //   portfolio: [
  //     {

  //       title: "Lanfranc Wholesale",
  //       category: "ecom",
  //       image: landranc,
  //       link: "https://www.walmart.com/seller/101330914?itemId=861444937&pageName=item&returnUrl=%2Fip%2FCharmin-Ultra-Gentle-Toilet-Paper-6-Mega-Rolls-286-Sheets-Per-Roll%2F861444937",
  //       desc: "Walmart offers Lanfranc Wholesale, a one-stop shop offering high quality products at unbeatable prices, ensuring affordability and convenience for all your needs.",
  //     },
  //     {

  //       title: "SRIARSH",
  //       category: "ecom",
  //       image: sriarch,
  //       link: "https://www.walmart.com/seller/101352648?itemId=557330560&pageName=item&returnUrl=%2Fip%2FWindex-Surface-Cleaners-Citrus-Scent-32-Fluid-Ounce%2F557330560",
  //       desc: "Walmart's one-stop shop, SRIARSH, offers a wide range of personal care and home essentials at unbeatable prices, transforming your everyday experience.",
  //     },
  //     {

  //       title: "Majestic Sellerz, LLC",
  //       category: "ecom",
  //       image: majestic,
  //       link: "https://www.walmart.com/seller/101124625?itemId=481160050&pageName=item&returnUrl=%2Fip%2FKinetic-Sand-Construction-Site-Folding-Sandbox-Playset-with-Vehicle-and-2lbs-Kinetic-Sand-for-Kids-Aged-3-and-up%2F481160050",
  //       desc: "Majestic Sellerz offers a selection of household and daily necessities, and seasonal delights, providing a magnificent shopping experience for a wide range of products.",
  //     },
  //     {

  //       title: "Focus Marketing",
  //       category: "ecom",
  //       image: focus,
  //       link: "https://www.walmart.com/seller/101288824?itemId=754320124&pageName=item&returnUrl=%2Fip%2FSoftsoap-Lustrous-Glow-Exfoliating-Body-Wash-Amber-and-Honey-20-Ounce%2F754320124",
  //       desc: "Focus Marketing offers a wide range of Household Essentials, focusing on quality, convenience, and personal care products to enhance your daily routine.",
  //     },
  //   ],
  // },
  {
    id: 3,
    mainTitle: "ECommerce",
    portfolio: [
      {
        title: "Vintage Wonders",
        category: "ecom",
        image: ecommerceBack1,
        mainTitle: "E-Commerce",
        logo: vintage,
        link: "https://vintagewonders.shop/",
        desc: "Vintage Wonders offers a collection of vintage-inspired Halloween costumes, transporting you back in time to enchanting frights and timeless elegance.",
      },
      {
        title: "BCBB Store",
        category: "ecom",
        image: ecommerceBack2,
        mainTitle: "E-Commerce",
        logo: bcbb,
        link: "https://bcbb.shop/",
        desc: "BCBB Store offers endless laughter and endless fun with its collection of playful essentials, transforming any space into a playground for cherished childhood memories.",
      },
      {
        title: "Brooks Market",
        category: "ecom",
        image: ecommerceBack3,
        mainTitle: "E-Commerce",
        logo: Brooks,
        link: "https://brooksmarket.shop/",
        desc: "Brooks Market offers a combine style and sophistication to elevate living spaces, offering a diverse range of decorative pieces to create an elegant haven.",
      },
      {
        title: "EICI Store",
        category: "ecom",
        image: ecommerceBack4,
        mainTitle: "E-Commerce",
        logo: eici,
        link: "https://eici.store/",
        desc: "Eici Store offers a premium selection of nutritious and delicious pet food, ensuring your pet enjoys every meal with wholesome and tail-wagging flavors.",
      },
    ],
  },
  {
    id: 4,
    mainTitle: "Web Development",
    portfolio: [
      {
        title: "NidoSpaces",
        category: "web",
        image: WebDevBack1,
        mainTitle: "Web Development",
        logo: nido,
        link: "https://nidospaces.store/",
        desc: "A fully modern website where user can buy bedsheets, cushions, lamps, living room items and decoration items, providing ease to the customer",
      },
      {
        title: "Timeless Management",
        category: "web",
        image: WebDevBack2,
        mainTitle: "Web Development",
        logo: timeless,
        link: "https://timelessmanagement.shop/",
        desc: "Timeless Management offers a collection of wristwatches, ranging from classic designs to masterpieces, showcasing style, precision, and craftsmanship.",
      },
      {
        title: "Morning Side",
        category: "web",
        image: WebDevBack3,
        mainTitle: "Web Development",
        logo: morningSide,
        link: "https://morningside.shop/",
        desc: "Web-based platform that allows users to buy Decoration pieces , providing a convenient and easy to use platform for users to buy assesible items.",
      },
      {
        title: "Benilli Empire",
        category: "web",
        image: WebDevBack4,
        mainTitle: "Web Development",
        logo: BenilliEmpire,
        link: "https://bellaniempire.com/",
        desc: "The Benelli Empire offers a curated selection of cutting-edge technology, blending timeless elegance with innovative solutions to enhance your lifestyle experience.",
      },
    ],
  },
  // {
  //   id: 5,
  //   mainTitle: "Digital Marketing",
  //   portfolio: [
  //     {
  //       title: "Project Management",
  //       category: "mobile",
  //       image: Project,
  //       link: "/",
  //       desc: "Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users",
  //     },
  //     {
  //       title: "Home Service",
  //       category: "mobile",
  //       image: HomeService,
  //       link: "/",
  //       desc: "A Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users",
  //     },
  //     {
  //       title: "Project Management",
  //       category: "mobile",
  //       image: Project,
  //       link: "/",
  //       desc: "Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users",
  //     },
  //     {
  //       title: "Home Service",
  //       category: "mobile",
  //       image: HomeService,
  //       link: "/",
  //       desc: "Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users",
  //     },
  //   ],
  // },
  {
    id: 6,
    mainTitle: "Graphic Designing",
    portfolio: [
      {
        title: "Neicy Shop Logo",
        category: "ui",
        image: GraphicBack1,
        mainTitle: "Graphic Design",
        logo: Neicy,
        link: "https://neicey.shop/",
        desc: "Neicy Shop's visual symphony showcases graceful curves, exuding a timeless allure and embodying the essence of elegance and modernity.",
      },
      {
        title: "Feni Logo",
        category: "ui",
        image: GraphicBack2,
        mainTitle: "Graphic Design",
        logo: FeniLogo,
        link: "https://fenii.shop/",
        desc: "The Feni Logo, a symbol of elegance and innovation, is a key element in the modern design of Feni Shop, showcasing the brand's commitment to innovation.",
      },
      {
        title: "Serenade Blossoms",
        category: "ui",
        image: GraphicBack3,
        mainTitle: "Graphic Design",
        logo: timelessBlack,
        link: "https://www.behance.net/gallery/185986225/Serenade-Blossoms",
        desc: "Serenade Blossoms, a whispers tale of nature's symphony through its delicate petals, creating a harmonious display of color and fragrance.",
      },
      {
        title: "Alpine Echoes of Night",
        category: "ui",
        image: GraphicBack4,
        mainTitle: "Graphic Design",
        logo: ar3,
        link: "https://www.behance.net/gallery/185983487/Alpine-Echoes-of-Night",
        desc: "Alpine Echoes of Night, a vector design, evokes the enchanting ambiance of moonlit peaks, showcasing the majesty of nature and the beauty of a full moon.",
      },
    ],
  },
];
