import { nido,Bcbb, Brooks,  HomeService, Karaeians,morningSide , BenilliEmpire, timeless, Project ,Benilli, FeniLogo,Neicy, ar3, timelessBlack } from '../assets';

export const data =[
    {
        id:1,
        title:'Project Management',
        category:'mobile',
        image:Project,
        link:'/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:2,
        title:'Neicy Shop Logo',
        category:'ui',
        image:Neicy,
        link:'https://neicey.shop/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:3,
        title:'NidoSpaces',
        category:'web',
        image:nido,
        link:'https://hoobankdemo.netlify.app/',
        desc:'A fully modern website where user can buy bedsheets, cushions, lamps, living room items and decoration items, providing ease to the customer',
    },
    {
        id:4,
        title:'BCBB Shop',
        category:'ecom',
        image:Bcbb,
        link:'https://bcbb.shop/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:5,
        title:'Home Service',
        category:'mobile',
        image:HomeService,
        link:'https://youtube-mirror.netlify.app/',
        desc:'A Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:6,
        title:'Feni Logo',
        category:'ui',
        image:FeniLogo,
        link:'https://fenii.shop/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:7,
        title:'Timeless Management',
        category:'web',
        image:timeless,
        link:'https://timelessmanagement.shop/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:8,
        title:'Kareaians Store',
        category:'ecom',
        image:Karaeians,
        link:'https://kkaraeins.store/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:9,
        title:'Project Management',
        category:'mobile',
        image:Project,
        link:'https://netflix-double.netlify.app/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:10,
        title:'Timeless Logo',
        category:'ui',
        image:timelessBlack,
        link:'https://timelessmanagement.shop/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:11,
        title:'Benilli Empire',
        category:'web',
        image:BenilliEmpire,
        link:'https://bellaniempire.com/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:12,
        title:'Benilli empire',
        category:'ecom',
        image:Benilli,
        link:'https://bellaniempire.com/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:13,
        title:'Home Service',
        category:'mobile',
        image:HomeService,
        link:'/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:14,
        title:'AR3 Discount Store Logo',
        category:'ui',
        image:ar3,
        link:'https://ar3discountstore.com/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
    {
        id:15,
        title:'Morning Side',
        category:'web',
        image:morningSide,
        link:'https://morningside.shop/',
        desc:'Web-based platform that allows users to buy Decoration pieces , providing a convenient and easy to use platform for users to buy assesible items.',
    },
    {
        id:16,
        title:'Brooks Market',
        category:'ecom',
        image:Brooks,
        link:'https://brooksmarket.shop/',
        desc:'Web application whre People can buy handfrees, Head set , Smart Watches, Laptops and VR set, providing excellence to the Users',
    },
];